#!/bin/sh
if [ -f "/root/.env" ] && [ -s "/root/.env" ];; then
  source .env
fi


# Check if UUID is set in the .env file
if [ -z "$UUID" ]; then
  echo "UUID is not set in .env file"
  exit 1
fi

if [ -z "PORT" ]; then
  echo "PORT is not set in .env file"
  exit 1
fi

sed -i "s/\$UUID/$UUID/g" /etc/xray/config.json
sed -i "s/\$PORT/$PORT/g" /etc/caddy/Caddyfile
echo "env variables applied"
